# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "centos-7-5"
  config.vm.box_check_update = false
  config.vm.hostname = "centos7-k5"  
  config.vm.network "public_network"
  config.vm.define "centos7-k5"
  config.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "1024"
  end
end
